### ISSUE TITLE
「かんたん配信」の配信内容を anzu-js-sdk で受信できるかどうかという点について明確になっていると良い

### ISSUE THREAD

**Issue by mhama** [shiguredo/anzu-help#2]
おそらく仕様なのじゃないかと思いますが、「かんたん配信」をsdkを利用して受信すべく、channel id指定でdownstreamをplayしようとしましたが、できませんでした。（ログに特別エラー等は出ていませんでした）

その後、upstreamをsdkで作成したところ、そのdownstreamはすんなり再生することができました。ということは、通常の受信方法では「かんたん配信」は受信・再生できないということと解釈しました。

同様のことを考えるユーザーさんが今後出る可能性もあると思いますので、「かんたん配信」のページに、sdkで受信する方法があるならその方法を、ないならその旨の記述がされているとベターのように思いました。

**Comment by voluntas** [comment]
@mhama ご指摘ありがとうございます。ご推察の通り「かんたん配信」は利用可能と明示しているチャネルとは別に、専用のチャンネルを使用しております。またそのチャネルは ListChannels などで取得できないようになっています。

かんたん配信は、かんたん配信専用のチャネルを使用しており、SDK などからは使用できずかんたん配信の中で閉じていることを明記するか、既存のチャネルを使用しての配信を使用可能にするか検討させていただきます。

フィードバックありがとうございます。大変ありがたいです。

**Comment by mhama** [comment]
@voluntas ご説明ありがとうございます。
そういう仕組みだったのですね。すっきりしました。:smile:
